#!/usr/bin/env bash
#
# Regenerates src/PipeWire.NET/generated/*.g.cs from the installed PipeWire headers.
# Run on Linux (or WSL) with libpipewire-0.3-dev and libclang-dev installed:
#
#   sudo apt-get install -y libpipewire-0.3-dev libclang-dev
#   dotnet tool install --global ClangSharpPInvokeGenerator --version 21.1.8.3
#   bash generate/generate.sh
#
# The generated files are committed; downstream consumers do not run this.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOOL="$HOME/.dotnet/tools/ClangSharpPInvokeGenerator"

if ! [ -x "$TOOL" ] && ! command -v ClangSharpPInvokeGenerator &>/dev/null; then
  echo "ERROR: ClangSharpPInvokeGenerator not found."
  echo "Install: dotnet tool install --global ClangSharpPInvokeGenerator --version 21.1.8.3"
  exit 1
fi
[ -x "$TOOL" ] || TOOL=ClangSharpPInvokeGenerator

if [ ! -f /usr/include/pipewire-0.3/pipewire/pipewire.h ]; then
  echo "ERROR: PipeWire headers not found at /usr/include/pipewire-0.3/."
  echo "Install: sudo apt-get install libpipewire-0.3-dev   (or pipewire-devel)"
  exit 1
fi

# The dotnet tool packaging does not bundle native libclang/libClangSharp; load them
# from the NuGet runtime packages on the LD path. The matching tool version (21.1.8)
# is needed; the .3 suffix on ClangSharpPInvokeGenerator only applies to the tool itself.
LIBCLANG_NATIVE="$HOME/.nuget/packages/libclang.runtime.linux-x64/21.1.8/runtimes/linux-x64/native"
CLANGSHARP_NATIVE="$HOME/.nuget/packages/libclangsharp.runtime.linux-x64/21.1.8/runtimes/linux-x64/native"

if [ ! -f "$LIBCLANG_NATIVE/libclang.so" ] || [ ! -f "$CLANGSHARP_NATIVE/libClangSharp.so" ]; then
  echo "ERROR: Native libclang / libClangSharp 21.1.8 not found at the expected NuGet cache paths."
  echo "Provision via:"
  echo "  mkdir /tmp/clangsharp-bootstrap && cd /tmp/clangsharp-bootstrap"
  echo "  dotnet new console -o dummy && cd dummy"
  echo "  dotnet add package libclang.runtime.linux-x64        --version 21.1.8"
  echo "  dotnet add package libClangSharp.runtime.linux-x64   --version 21.1.8"
  exit 1
fi

export LD_LIBRARY_PATH="$LIBCLANG_NATIVE:$CLANGSHARP_NATIVE:${LD_LIBRARY_PATH:-}"

# Auto-detect clang's bundled C standard headers (stdbool.h, stddef.h, ...)
CLANG_INC="$(ls -d /usr/lib/llvm-*/lib/clang/*/include 2>/dev/null | head -1)"
if [ -z "$CLANG_INC" ]; then
  echo "ERROR: clang builtin include dir not found. Install: sudo apt-get install libclang-dev"
  exit 1
fi

OUT="$REPO_ROOT/src/PipeWire.NET/generated"
mkdir -p "$OUT"
# Wipe the entire generated/ directory. Hand-written code lives in
# src/PipeWire.NET/Native.Extensions.cs (same Generated namespace and same
# `Native` partial class), NOT here - see that file for the rationale.
rm -f "$OUT"/*.cs "$OUT"/*.g.cs

WORK=$(mktemp -d)
trap "rm -rf $WORK" EXIT
cd "$WORK"

# NOTE on traversal: ClangSharp's --traverse matches whole file paths, not
# directory prefixes (a bare dir traverses nothing; verified empirically), and it
# has no "traverse everything reachable" mode. So the set of headers to emit is an
# explicit list in pipewire.rsp. It is curated deliberately - adding a header there
# is the way to expose more native surface. Keep it in sync when bumping PipeWire.

# Header file prepended to each generated file - keeps generated types public while
# suppressing missing-XML-doc warnings and a few naming-style analyzers.
cat > header.txt << 'HEADER'
// <auto-generated/>
// Generated by ClangSharpPInvokeGenerator from libpipewire-0.3 headers.
// Run generate/generate.sh to regenerate.

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
#pragma warning disable CA1707 // Identifiers should not contain underscores
#pragma warning disable CA1711 // Identifiers should not have incorrect suffix
#pragma warning disable CA1716 // Identifiers should not match keywords
#pragma warning disable CA1720 // Identifiers should not contain type names
#pragma warning disable CA1815 // Override Equals and operator equals on value types
HEADER

"$TOOL" "@$REPO_ROOT/generate/pipewire.rsp" \
  --file "$REPO_ROOT/generate/pipewire_composite.h" \
  --headerFile "$WORK/header.txt" \
  --include-directory "$CLANG_INC" \
  --output "$WORK"

EXIT=$?
if [ $EXIT -ne 0 ]; then
  echo "Generator failed with exit $EXIT."
  exit $EXIT
fi

# Rename plain .cs to .g.cs and copy into the repo
for f in "$WORK"/*.cs; do
  base=$(basename "$f" .cs)
  cp "$f" "$OUT/${base}.g.cs"
done

count=$(ls "$OUT"/*.g.cs 2>/dev/null | wc -l)
loc=$(wc -l "$OUT"/*.g.cs 2>/dev/null | tail -1 | awk '{print $1}')
echo "Generated $count files / $loc LOC into $OUT"
echo "Review the diff and commit."
